#+TITLE: My Emacs Configuration
#+AUTHOR: Dimitris Spythouris
#+STARTUP: overview
#+OPTIONS: num:nil

* Package Init
** Archives
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(package-initialize)

(when (not package-archive-contents)
    (ignore-errors (package-refresh-contents)))
#+END_SRC

** Use-package
#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(eval-when-compile (require 'use-package))
#+END_SRC

* Core Settings
** Font
The font used.
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(font . "JuliaMono 10" ))
(set-face-attribute 'default nil :family "JuliaMono" :height 100 :weight 'normal)
#+END_SRC

** Starting Directory
Configure emacs to start in the home directory.
#+BEGIN_SRC emacs-lisp
(setq default-directory "~/")
#+END_SRC

** Scrolling
Smooth scrolling.
#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-scroll-amount '(3 ((shift) . 3)))
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-follow-mouse 't)
(setq scroll-step 1)
#+END_SRC

** Column numbers
#+BEGIN_SRC emacs-lisp
(setq column-number-mode t)
#+END_SRC

** Splash Screen
Skip the splash screen/message and make the scratch buffer empty.
#+BEGIN_SRC emacs-lisp
(setq inhibit-splash-screen t)
(setq initial-scratch-message nil)
(setq inhibit-startup-echo-message t)
#+END_SRC

** Bars
Turn off the scroll bar, menu bar and the tool bar.
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+END_SRC

** Indentation
Default tab width is 4 and tabs are now spaces.
#+BEGIN_SRC emacs-lisp
(setq-default tab-always-indent t)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
#+END_SRC

** Backup Files
All backup files are saved in the ~/.emacs.d/saves directory.
Some versioning of files is used to prevent disasters.
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist '(("." . "~/.emacs.d/saves"))
  backup-by-copying t
  version-control t
  delete-old-versions t
  kept-new-versions 20
  kept-old-versions 5
  )
#+END_SRC

** Yes/No
When emacs requires a yes/no answer make it one character.
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Visual lines
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode t)
#+END_SRC

** Disabled Commands
Enable all disabled commands.
#+BEGIN_SRC emacs-lisp
(setq disabled-command-function nil)
#+END_SRC

** Sentences
Sentences end on a dot and one space. This is used to improve sentence
navigation with ~M-a~ and ~M-e~.
#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space nil)
#+END_SRC

** Misc
#+BEGIN_SRC emacs-lisp
(use-package newcomment
  :bind
  ("C-x M-;" . comment-box))

(use-package view
  :bind ("C-v" . View-scroll-half-page-forward)
        ("M-v" . View-scroll-half-page-backward))

(use-package align
  :bind ("C-c e a a" . align)
        ("C-c e a r" . align-regexp)
        ("C-c e a s" . align-current))

(use-package emacs
  :bind
  ("C-M-<left>"  . shrink-window-horizontally)
  ("C-M-<right>" . enlarge-window-horizontally)
  ("C-M-<down>"  . shrink-window)
  ("C-M-<up>"    . enlarge-window)
  ("M-o"         . other-window)
  ("C-<tab>"     . indent-relative)
  ("<f5>"        . compile)
  ("C-<f5>"      . recompile)
  ("<C-f9>"      . set-frame-font)
  ("C-x C-b"     . ibuffer)
  ("<f7>"        . toggle-transparency)
  ("M-j"         . (lambda () (interactive) (join-line -1)))
  :config
  (setq window-divider-default-right-width 1)
  (setq window-divider-default-bottom-width 1)
  (setq window-divider-default-places 'right-only)
  :hook (after-init . window-divider-mode))
#+END_SRC

* Base Package Settings
** Eshell
#+BEGIN_SRC emacs-lisp
(use-package eshell
  :hook (eshell-mode .
    (lambda ()
      (eshell/alias "c" "clear 1")
      (eshell/alias "f" "find-file $1")
      (eshell/alias "fo" "find-file-other-window $1")
      (eshell/alias "d" "dired $1")
      (eshell/alias "ll" "ls -l")
      (eshell/alias "la" "ls -al"))))
#+END_SRC

** Re-builder
#+BEGIN_SRC emacs-lisp
(use-package re-builder
  :config
  (setq reb-re-syntax 'string))
#+END_SRC

** Flymake
#+BEGIN_SRC emacs-lisp
(use-package flymake
  :config
  (setq flymake-no-changes-timeout nil)
  (setq flymake-start-syntax-check-on-newline nil))
#+END_SRC

** Dired
Guess resulting directory on dired operations
#+BEGIN_SRC emacs-lisp
(setq dired-dwim-target t)
#+END_SRC

** Winner-mode
   Easily undo and redo window changes.
   #+BEGIN_SRC emacs-lisp
(use-package winner
  :demand
  :config
  (winner-mode 1)
  :bind
  ("C-c w u" . winner-undo)
  ("C-c w r" . winner-redo))
   #+END_SRC

** Org-mode
#+BEGIN_SRC emacs-lisp
(use-package org
  :config
  (setq org-agenda-span 14)
  (setq org-agenda-files (quote ("~/notes/schedule.org")))
  (setq org-src-window-setup 'current-window)
  (setq org-src-fontify-natively t)
  (setq org-list-allow-alphabetical t)
  (setq org-src-preserve-indentation t)
  (setq org-src-tab-acts-natively t)
  (setq org-edit-src-content-indentation 0)
  :bind
  ("C-c o a" . org-agenda)
  ("C-c c"   . org-capture)
  ("C-c o l" . org-store-link))
#+END_SRC

** Electric
   Enable electric pair and indent mode.
   A newline between adjacent parentheses opens an extra one.
   #+BEGIN_SRC emacs-lisp
(use-package electric
  :config
  (electric-pair-mode 1)
  (electric-indent-mode 1)
  (setq electric-pair-open-newline-between-pairs t))
   #+END_SRC

** Isearch
   Make isearch search for regexes by default.
   #+BEGIN_SRC emacs-lisp
(use-package isearch
  :bind
  ("C-s" . isearch-forward-regexp))
   #+END_SRC

** Show-paren-mode
   Highlight matching parentheses.
   #+BEGIN_SRC emacs-lisp
(use-package paren
  :config
  (setq show-paren-style 'parenthesis)
  (setq show-paren-when-point-in-periphery t)
  (setq show-paren-when-point-inside-paren nil)
  (show-paren-mode 1))
   #+END_SRC

** Hippie-expand
#+BEGIN_SRC emacs-lisp
(use-package hippie-exp
  :bind
  ("M-/" . hippie-expand)
  :config
  (setq hippie-expand-try-functions-list '(try-expand-dabbrev-visible
                                           try-expand-dabbrev
                                           try-expand-dabbrev-all-buffers
                                           try-expand-dabbrev-from-kill
                                           try-complete-file-name-partially
                                           try-complete-file-name
                                           try-expand-all-abbrevs
                                           try-expand-list
                                           try-expand-line
                                           try-expand-dabbrev-from-kill
                                           try-complete-lisp-symbol-partially
                                           try-complete-lisp-symbol)))
#+END_SRC

* Other Package Settings
** Avy
#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  :bind ("C-;" . avy-goto-char))
#+END_SRC

** Xterm-color
   #+BEGIN_SRC emacs-lisp
   (use-package xterm-color
     :ensure t
     :config
     (setq compilation-environment '("TERM=xterm-256color"))
     (defun my/advice-compilation-filter (f proc string)
       (funcall f proc (xterm-color-filter string)))
     (advice-add 'compilation-filter :around #'my/advice-compilation-filter))
   #+END_SRC

** Deft
#+BEGIN_SRC emacs-lisp
(use-package deft
  :ensure t
  :init
  (setq deft-directory "~/notes"
        deft-extensions '("org")
        deft-use-filename-as-title t
        deft-recursive t
        deft-new-file-format "%Y-%m-%dT%H%M"))
#+END_SRC

** Zetteldeft
#+BEGIN_SRC emacs-lisp
(use-package zetteldeft
  :ensure t
  :after deft
  :bind (("C-c n f" . zetteldeft-find-file)
         ("C-c n n" . zetteldeft-new-file)
         ("C-c n N" . zetteldeft-new-file-and-link)
         ("C-c n i" . zetteldeft-find-file-id-insert)
         ("C-c n l" . zetteldeft-follow-link)
         ("C-c n a l" . zetteldeft-avy-link-search)
         ("C-c n a t" . zetteldeft-avy-tag-search)
         ("C-c n s" . zetteldeft-search-at-point)
         ("C-c n c" . zetteldeft-search-current-id)))
#+END_SRC

** Ivy, Counsel, Swiper
Enable ivy globally (replacement for ido).
#+BEGIN_SRC emacs-lisp
(use-package ivy
  :diminish ivy-mode
  :ensure t
  :bind (("C-c C-r" . ivy-resume))
  :config
    (ivy-mode t)
    (setq ivy-initial-inputs-alist nil)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-count-format "(%d/%d) ")
  )
#+END_SRC

   Enable swiper (enhanced isearch for ivy) and assign C-s to search
#+BEGIN_SRC emacs-lisp
(use-package swiper
  :ensure t)
#+END_SRC

   Counsel is a collection of ivy enhanced base commands
   Bind some keys to common commands
#+BEGIN_SRC emacs-lisp
(use-package counsel
  :ensure t
  ;; :config
  ;; (counsel-mode t)
  :bind (("C-x C-f"   . counsel-find-file)
         ("<f2> u"    . counsel-unicode-char)
         ("C-M-s"     . counsel-grep-or-swiper)
         ("C-c s g f" . counsel-git)
         ("C-c s d"   . counsel-dired-jump)
         ("C-c s g g" . counsel-git-grep)
         ("C-c s f"   . counsel-fzf)
         ("C-c s l"   . counsel-locate)
         ("C-x r i"   . counsel-register)
         ("M-i"       . counsel-imenu)
         ("<f9>"      . counsel-load-theme)))
#+END_SRC

** Ripgrep
#+BEGIN_SRC emacs-lisp
(use-package ripgrep
  :ensure t)
#+END_SRC

** AMX
Replacement for smex with good recents support and counsel integration
#+BEGIN_SRC emacs-lisp
(use-package amx
  :ensure t
  :config
  (setq amx-backend 'auto)
  (setq amx-save-file "~/.emacs.d/amx-items")
  (setq amx-history-length 50)
  (amx-mode 1)
  :bind
  ("M-x". amx))
#+End_SRC

** Flycheck
Load flycheck
#+BEGIN_SRC emacs-lisp
(use-package flycheck
  :ensure t
  :config
  (setq flycheck-check-syntax-automatically '(save mode-enabled)))
#+END_SRC

** Yasnippet
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :ensure t
  :diminish yas-minor-mode
  :config
  ;; (setq yas-snippet-dirs '("~/.emacs.d/snippets"))
  (yas-global-mode)
  :bind
  ("C-c C-<tab>"    . company-yasnippet)
  ("C-c <tab>". yas-expand))
#+END_SRC

** All-the-icons
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-dired
  :ensure t
  :hook
  (dired-mode . all-the-icons-dired-mode))

(use-package all-the-icons-ivy
  :ensure t
  :config
  (setq all-the-icons-ivy-file-commands
    '(counsel-find-file
      counsel-file-jump
      counsel-recentf
      projectile-find-file
      projectile-find-dir))
  (all-the-icons-ivy-setup)
  (ivy-set-display-transformer 'ivy-switch-buffer 'all-the-icons-ivy-buffer-transformer))
#+END_SRC

** Company
   Enable company with various settings
#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :diminish
  :config
   (setq company-idle-delay 0.1)
   (setq company-minimum-prefix-length 1)
   (setq company-selection-wrap-around t)
   (setq company-tooltip-align-annotations t)
   (setq company-tooltip-limit 10)
   (setq company-dabbrev-downcase nil)
   (company-tng-configure-default))
#+END_SRC

** Projectile
#+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :config
  (setq projectile-completion-system 'ivy)
  (setq projectile-tags-backend 'etags-select)
  (add-to-list 'projectile-globally-ignored-modes "org-mode")
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
  (projectile-mode +1))
#+END_SRC

** Eglot
#+BEGIN_SRC emacs-lisp
(use-package eglot
  :ensure t
  :bind (:map rustic-mode-map
              ("C-c l c" . eglot-code-actions))
  :config
  (add-to-list 'eglot-server-programs '(haskell-mode . ("ghcide" "--lsp")))
  (add-to-list 'eglot-server-programs '(nim-mode     . ("nimlsp")))
  (add-to-list 'eglot-server-programs '(c-mode       . ("clangd")))
  (add-to-list 'eglot-server-programs '(c++-mode     . ("clangd")))
  (add-to-list 'eglot-server-programs '(rust-mode    . ("rust-analyzer")))
  (add-to-list 'eglot-server-programs '((tex-mode context-mode texinfo-mode bibtex-mode)
                                        . ("digestif"))))
#+END_SRC

** Magit
Magit is an interface to git.
We also install magit-annex for git-annex compatibility.
Access it with C-x g.
#+BEGIN_SRC emacs-lisp
(use-package magit
  :ensure t
  :bind ("C-x g". magit-status))
#+END_SRC

** Which-key
   Which-key is a keybinding preview utility to show all subsequent keys when waiting for commands.
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :diminish which-key-mode
  :config
    (which-key-mode t))
#+END_SRC

** Iedit
#+BEGIN_SRC emacs-lisp
(use-package iedit
  :ensure t
    :bind ("C-c i" . iedit-mode))
#+END_SRC

** Org Bullets
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
  :ensure t
  :hook (org-mode . org-bullets-mode))
#+END_SRC

** Latex
#+BEGIN_SRC emacs-lisp
(use-package tex
  :defer t
  :ensure auctex
  :hook
  (LaTeX-mode . eglot-ensure)
  (LaTeX-mode . company-mode)
  :config
  (setq TeX-auto-save t)
  (setq TeX-engine 'luatex)
  (setq TeX-parse-self t))
#+END_SRC

** Quickrun
   Quickrun provides utilities to quickly compile and execute programs
   F6 runs a program in eshell
#+BEGIN_SRC emacs-lisp
(use-package quickrun
  :ensure t
  :bind ("<f6>" . quickrun-shell))
#+END_SRC

** Emmet
   Offers snippets for html and css
#+BEGIN_SRC emacs-lisp
(use-package emmet-mode
  :ensure t
  :hook ((sgml-mode . emmet-mode)
         (css-mode . emmet-mode)))
#+END_SRC

** Neotree
#+BEGIN_SRC emacs-lisp
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-directory-name-transformer    #'identity
          treemacs-display-in-side-window        t
          treemacs-eldoc-display                 t
          treemacs-file-event-delay              5000
          treemacs-file-extension-regex          treemacs-last-period-regex-value
          treemacs-file-follow-delay             0.2
          treemacs-file-name-transformer         #'identity
          treemacs-follow-after-init             t
          treemacs-git-command-pipe              ""
          treemacs-goto-tag-strategy             'refetch-index
          treemacs-indentation                   2
          treemacs-indentation-string            " "
          treemacs-is-never-other-window         t
          treemacs-max-git-entries               5000
          treemacs-missing-project-action        'ask
          treemacs-move-forward-on-expand        nil
          treemacs-no-png-images                 nil
          treemacs-no-delete-other-windows       t
          treemacs-project-follow-cleanup        nil
          treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-position                      'left
          treemacs-recenter-distance             0.1
          treemacs-recenter-after-file-follow    nil
          treemacs-recenter-after-tag-follow     nil
          treemacs-recenter-after-project-jump   'always
          treemacs-recenter-after-project-expand 'on-distance
          treemacs-show-cursor                   nil
          treemacs-show-hidden-files             t
          treemacs-silent-filewatch              nil
          treemacs-silent-refresh                nil
          treemacs-sorting                       'alphabetic-asc
          treemacs-space-between-root-nodes      t
          treemacs-tag-follow-cleanup            t
          treemacs-tag-follow-delay              1.5
          treemacs-user-mode-line-format         nil
          treemacs-width                         35)
    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))

(use-package treemacs-projectile
  :after treemacs projectile
  :ensure t)

(use-package treemacs-icons-dired
  :after treemacs dired
  :ensure t
  :config (treemacs-icons-dired-mode))

(use-package treemacs-magit
  :after treemacs magit
  :ensure t)
#+END_SRC

** Paredit
#+BEGIN_SRC emacs-lisp
(use-package paredit
  :ensure t)
#+END_SRC

** Aggressive-indent-mode
#+BEGIN_SRC emacs-lisp
(use-package aggressive-indent
  :ensure t
  :hook
  (html-mode . aggressive-indent-mode)
  (css-mode  . aggressive-indent-mode)
  (clojure-mode . aggressive-indent-mode))
#+END_SRC

** Htmlize
#+BEGIN_SRC emacs-lisp
(use-package htmlize :ensure t)
#+END_SRC

** Hindent
#+BEGIN_SRC emacs-lisp
(use-package hindent :ensure t)
#+END_SRC

** Rainbow delimiters
#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
  :ensure t)
#+END_SRC

** Rust-lang
#+begin_src emacs-lisp
(use-package rustic
  :ensure t
  :mode "\\.rs\\'"
  :hook
  (rustic-mode . (lambda () (flymake-mode -1)))
  (rustic-mode . company-mode)
  :config
  (setq rustic-lsp-server 'rust-analyzer)
  (setq rustic-lsp-client 'eglot)
  (setq rustic-format-on-save nil))
#+end_src

** Clojure-lang
*** Cider
#+BEGIN_SRC emacs-lisp
(use-package cider
  :ensure t
  :bind (:map cider-repl-mode-map
              ("C-c C-k" . cider-repl-clear-buffer)))
#+END_SRC

*** Clojure-mode
#+BEGIN_SRC emacs-lisp
(use-package clojure-mode
  :ensure t
  :hook
  (clojure-mode . company-mode)
  (clojure-mode . rainbow-delimiters-mode)
  (clojure-mode . paredit-mode))
#+END_SRC

** Yaml-lang
*** YAML-mode
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode :ensure t)
#+END_SRC

** Nim-lang
*** Nim-mode
#+BEGIN_SRC emacs-lisp
(use-package nim-mode
  :hook
  (nim-mode . eglot-ensure)
  (nim-mode . company-mode)
  :ensure t)
#+END_SRC

** C/C++-lang
*** C-mode
Tab = 4 spaces, bsd indentation style
#+BEGIN_SRC emacs-lisp
(use-package cc-mode
  :hook
  (c-mode . eglot-ensure)
  (c-mode . company-mode)
  :config
  (setq-default c-basic-offset 4)
  (setq-default c-default-style "bsd"))
#+END_SRC

#+begin_src emacs-lisp
(use-package c++-mode
  :hook
  (c++-mode . eglot-ensure)
  (c++-mode . company-mode))
#+end_src

** Js-lang
*** Js-mode
#+BEGIN_SRC emacs-lisp
(use-package js
  :hook
  (js-mode . flycheck-mode)
  (js-mode . company-mode)
  (js-mode . subword-mode))
#+END_SRC

** Haskell-lang
*** Haskell-mode
#+BEGIN_SRC emacs-lisp
  (use-package haskell-mode
    :ensure t
    :bind (:map haskell-mode-map
          ("C-c C-c" . haskell-compile)
          ("C-c C-l" . haskell-process-load-or-reload)
          ("C-`"     . haskell-interactive-bring)
          ("C-c C-t" . haskell-process-do-type)
          ("C-c C-i" . haskell-process-do-info)
          ("C-c C-k" . haskell-interactive-mode-clear))
    :config
    (setq haskell-interactive-popup-errors nil
          haskell-process-auto-import-loaded-modules t
          haskell-process-log t
          haskell-process-type 'stack-ghci
          ;haskell-tags-on-save t
          haskell-compile-cabal-build-command "stack build"
          haskell-process-suggest-hoogle-imports t)
    :hook
    ((haskell-mode . haskell-indentation-mode)
     (haskell-mode . interactive-haskell-mode)
     (haskell-mode . company-mode)
     (haskell-mode . flycheck-mode)
     (haskell-mode . hindent-mode)
     (haskell-mode . subword-mode)))
#+END_SRC

** Css-lang
*** CSS-mode
#+BEGIN_SRC emacs-lisp
(use-package css-mode
  :ensure t
  :hook
  (css-mode . company-mode))
#+END_SRC

** Themes
Install the themes and set the default one
#+BEGIN_SRC emacs-lisp
(use-package ujelly-theme :ensure t)
(use-package doom-themes :ensure t)
(load-theme 'doom-tomorrow-night t)
#+END_SRC

** Smart-modeline
#+BEGIN_SRC emacs-lisp
(use-package smart-mode-line
  :ensure t
  :config
  (setq sml/no-confirm-load-theme t)
  (sml/setup)
  (sml/apply-theme 'respectful))
#+END_SRC

* My functions
  Indent the whole buffer
#+BEGIN_SRC emacs-lisp
(defun iwb ()
  "indent whole buffer"
  (interactive)
  (delete-trailing-whitespace)
  (indent-region (point-min) (point-max) nil)
  (untabify (point-min) (point-max)))
#+END_SRC

